# .github/workflows/deploy-docker.yml - Alternative dengan Docker
name: Deploy with Docker

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build with Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          node:18-alpine \
          sh -c "
            npm cache clean --force &&
            rm -f package-lock.json &&
            npm install &&
            npm run build
          "
      env:
        NODE_ENV: production
        GITHUB_PAGES: true
        GITHUB_REPOSITORY: ${{ github.repository }}
        
    - name: Create .nojekyll file
      run: touch ./dist/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4